// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"sub2api-enhance/internal/config"
	"sub2api-enhance/internal/notify"
	"sub2api-enhance/internal/thirdpartypromptaudit"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func initializeCore(db *sql.DB, cfg *config.Config, captures *thirdpartypromptaudit.CaptureStore) (*Core, error) {
	repository := thirdpartypromptaudit.NewRepository(db)
	encryptor, err := config.NewEncryptor(cfg)
	if err != nil {
		return nil, err
	}
	configManager := thirdpartypromptaudit.NewConfigManager(db, encryptor, cfg)
	modelClient := thirdpartypromptaudit.NewModelClient(repository, configManager)
	evaluator := thirdpartypromptaudit.NewEvaluator(repository, modelClient, configManager)
	smtp := notify.NewSMTP(cfg)
	service := thirdpartypromptaudit.NewService(repository, configManager, evaluator, modelClient, smtp)
	adminHandler := thirdpartypromptaudit.NewAdminHandler(service, configManager, repository, captures)
	core := &Core{
		Service: service,
		Handler: adminHandler,
	}
	return core, nil
}
