<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {useI18n} from 'vue-i18n'
import {quotaFollowAPI as api,type FollowConfig,type FollowRuntime,type ResetRecord,type RecordDetail} from '@/api/quota-follow'
import {getAll} from '@/api/admin/groups'
import type {AdminGroup} from '@/types'
import {useAppStore} from '@/stores/app'
import {extractApiErrorMessage} from '@/utils/apiError'
import BaseDialog from '@/components/common/BaseDialog.vue'
import SystemUpdatePanel from '@/features/system-update/SystemUpdatePanel.vue'
const {t,te}=useI18n(),app=useAppStore()
const label=(key:string)=>te(`quotaFollow.${key}`)?t(`quotaFollow.${key}`):key
const groups=ref<AdminGroup[]>([]),runtime=ref<FollowRuntime|null>(null),userCount=ref(0),revision=ref(1)
const config=reactive<FollowConfig>({enabled:false,group_id:null,reset_weekly_enabled:true,reset_daily_enabled:false,min_interval_minutes:10,max_interval_minutes:15,observe_only:true})
const events=ref<{id:number;reset_at:string;status:string}[]>([]),eventPage=ref(1),eventTotal=ref(0),eventDetail=ref<unknown>(null)
const loading=ref(false),saving=ref(false),error=ref(''),items=ref<ResetRecord[]>([]),total=ref(0),page=ref(1),selected=ref<RecordDetail|null>(null),reconciling=ref(false)
const filter=reactive({source:'',source_detail:'',window:'',status:'',keyword:'',from:'',to:''})
const time=(value:string|null|undefined)=>value?new Date(value).toLocaleString():'—'
async function loadEvents(){const result=await api.events(eventPage.value);events.value=result.items;eventTotal.value=result.total}
async function inspectEvent(id:number){try{eventDetail.value=await api.event(id)}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}}
async function eventTurn(step:number){eventPage.value+=step;try{await loadEvents()}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}}
async function records(){const {from,to,...rest}=filter;const result=await api.records({...rest,from:from?new Date(from).toISOString():undefined,to:to?new Date(to).toISOString():undefined,page:page.value,page_size:20});items.value=result.items;total.value=result.total}
async function refresh(loadConfig=false){loading.value=true;error.value='';try{
 if(loadConfig){const value=await api.config();revision.value=value.revision;Object.assign(config,{enabled:value.enabled,group_id:value.group_id,reset_weekly_enabled:value.reset_weekly_enabled,reset_daily_enabled:value.reset_daily_enabled,min_interval_minutes:value.min_interval_minutes,max_interval_minutes:value.max_interval_minutes,observe_only:value.observe_only})}
 const results=await Promise.allSettled([getAll(),api.runtime(),api.discovery(),records(),loadEvents()]);if(results[0].status==='fulfilled')groups.value=results[0].value;if(results[1].status==='fulfilled')runtime.value=results[1].value;if(results[2].status==='fulfilled')userCount.value=results[2].value.users.length
 error.value=results.filter(r=>r.status==='rejected').map(r=>extractApiErrorMessage((r as PromiseRejectedResult).reason,label('failure'))).join('；')
 }catch(e){error.value=extractApiErrorMessage(e,label('failure'))}finally{loading.value=false}}
async function save(){saving.value=true;try{const value=await api.save({...config},revision.value);revision.value=value.revision;app.showSuccess(label('saved'));await refresh()}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}finally{saving.value=false}}
async function search(){try{await records()}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}}
async function detail(id:number){try{selected.value=await api.detail(id)}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}}
async function reconcile(){if(!selected.value?.delivery)return;reconciling.value=true;try{await api.reconcile(selected.value.delivery.id);await detail(selected.value.record.id);app.showSuccess(label('reconciled'));await records()}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}finally{reconciling.value=false}}
async function repairCache(){if(!selected.value)return;reconciling.value=true;try{await api.repairCache(selected.value.record.id);await detail(selected.value.record.id);app.showSuccess(label('repairScheduled'))}catch(e){app.showError(extractApiErrorMessage(e,label('failure')))}finally{reconciling.value=false}}
onMounted(()=>refresh(true))
</script>
<template><main class="enhance-page enhance-shell space-y-6 p-4 pt-3 sm:p-6 sm:pt-4">
 <header><div class="mb-2 flex flex-wrap items-center gap-3"><p class="text-sm font-semibold text-primary-600">sub2api++</p><SystemUpdatePanel /></div><h1 class="text-2xl font-bold sm:text-3xl">{{label('title')}}</h1><p class="mt-3 text-gray-500">{{label('description')}}</p></header>
 <p class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200" data-test="boundary">{{label('boundary')}}</p>
 <p v-if="error" role="alert" class="text-red-600">{{error}}</p>
 <form class="card space-y-5" @submit.prevent="save"><div class="flex items-center justify-between"><h2 class="text-xl font-semibold">{{label('settings')}}</h2><span class="text-sm text-gray-500">{{label('revision')}} {{revision}}</span></div>
  <div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><label class="space-y-2"><span class="label">{{label('group')}}</span><select v-model="config.group_id" class="input" :required="config.enabled" data-test="group"><option :value="null">{{label('chooseGroup')}}</option><option v-for="group in groups" :key="group.id" :value="group.id">{{group.name}} · #{{group.id}}</option></select></label><label class="space-y-2"><span class="label">{{label('minInterval')}}</span><input v-model.number="config.min_interval_minutes" class="input" type="number" min="1" required></label><label class="space-y-2"><span class="label">{{label('maxInterval')}}</span><input v-model.number="config.max_interval_minutes" class="input" type="number" :min="config.min_interval_minutes" required></label></div>
  <div class="flex flex-wrap gap-6"><label class="flex items-center gap-2"><input v-model="config.enabled" type="checkbox" data-test="enabled">{{label('enabled')}}</label><label class="flex items-center gap-2"><input v-model="config.reset_weekly_enabled" type="checkbox">{{label('weekly')}}</label><label class="flex items-center gap-2"><input v-model="config.reset_daily_enabled" type="checkbox">{{label('daily')}}</label><label class="flex items-center gap-2"><input v-model="config.observe_only" type="checkbox" data-test="observe">{{label('observe')}}</label></div>
  <p class="text-sm text-gray-500">{{label('eventHint')}}</p><div class="flex gap-3"><button class="btn btn-primary" type="submit" :disabled="saving||loading">{{label('save')}}</button><button class="btn btn-secondary" type="button" :disabled="loading" @click="refresh()">{{label('refresh')}}</button></div>
  <div v-if="runtime" class="grid gap-3 border-t pt-4 text-sm dark:border-dark-700 sm:grid-cols-2 lg:grid-cols-3"><p>{{label('accountCount')}}：{{runtime.accounts.length}}</p><p>{{label('userCount')}}：{{userCount}}</p><p>{{label('lastEvent')}}：{{time(runtime.last_event_at)}}</p><p>{{label('lastCheck')}}：{{time(runtime.last_checked_at)}}</p><p>{{label('nextCheck')}}：{{time(runtime.next_check_at)}}</p><p>{{label('redis')}}：{{runtime.redis_status}}</p><p class="sm:col-span-2">{{label('timezone')}}：{{runtime.original_timezone||label('unknownTimezone')}}</p></div><p v-if="runtime?.last_error" class="text-red-600">{{runtime.last_error}}</p><p v-if="runtime?.carryover_error" class="text-amber-700 dark:text-amber-300">{{runtime.carryover_error}}</p><p v-if="runtime?.collector_error" class="text-red-600">{{runtime.collector_error}}</p>
 </form>
 <section class="card space-y-4" data-test="records"><h2 class="text-xl font-semibold">{{label('records')}}</h2><p class="text-sm text-gray-500">{{label('recordsHint')}}</p><form class="flex flex-wrap items-end gap-3" @submit.prevent="page=1;search()">
  <label><span class="label">{{label('source')}}</span><select v-model="filter.source" class="input"><option value="">{{label('all')}}</option><option v-for="value in ['sub2api','enhance']" :key="value" :value="value">{{label(value)}}</option></select></label>
  <label><span class="label">{{label('trigger')}}</span><select v-model="filter.source_detail" class="input"><option value="">{{label('all')}}</option><option v-for="value in ['manual','openai_consensus','weekly_carryover','natural_daily','natural_weekly','pending_attribution','unattributed']" :key="value" :value="value">{{label(value)}}</option></select></label>
  <label><span class="label">{{label('window')}}</span><select v-model="filter.window" class="input"><option value="">{{label('all')}}</option><option value="daily">{{label('daily')}}</option><option value="weekly">{{label('weekly')}}</option></select></label>
  <label><span class="label">{{label('result')}}</span><select v-model="filter.status" class="input"><option value="">{{label('all')}}</option><option v-for="value in ['pending','inflight','succeeded','failed','skipped','uncertain','pending_attribution']" :key="value" :value="value">{{label(value)}}</option></select></label>
  <label><span class="label">{{label('from')}}</span><input v-model="filter.from" class="input" type="datetime-local"></label><label><span class="label">{{label('to')}}</span><input v-model="filter.to" class="input" type="datetime-local"></label><input v-model="filter.keyword" class="input max-w-xs" :placeholder="label('keyword')"><button class="btn btn-secondary" type="submit">{{label('filter')}}</button>
 </form><div class="overflow-auto"><table class="table"><thead><tr><th>{{label('time')}}</th><th>{{label('source')}}</th><th>{{label('trigger')}}</th><th>{{label('action')}}</th><th>{{label('evidence')}}</th><th>{{label('user')}}</th><th>{{label('window')}}</th><th>{{label('usageChange')}}</th><th>{{label('accounts')}}</th><th>{{label('result')}}</th><th/></tr></thead><tbody><tr v-for="record in items" :key="record.id"><td>{{time(record.occurred_at)}}</td><td><span class="rounded bg-primary-50 px-2 py-1 text-primary-800 dark:bg-primary-950 dark:text-primary-200">{{label(record.source)}}</span></td><td>{{label(record.source_detail)}}</td><td>{{label(record.action_type)}}</td><td>{{label(record.evidence_type)}}</td><td>{{record.username}} #{{record.user_id}}</td><td>{{record.window?label(record.window):'—'}}</td><td>{{record.before_usage_usd??'—'}} → {{record.after_usage_usd??'—'}}</td><td>{{record.accounts?.map(a=>a.name).join('、')||'—'}}</td><td>{{label(record.status)}}</td><td><button class="text-primary-600 underline" @click="detail(record.id)">{{label('details')}}</button></td></tr></tbody></table><p v-if="!items.length" class="py-8 text-center text-gray-500">{{label('empty')}}</p></div><footer class="flex justify-end gap-3"><span>{{total}} · {{page}}</span><button class="btn btn-secondary" :disabled="page<=1" @click="page--;search()">←</button><button class="btn btn-secondary" :disabled="page*20>=total" @click="page++;search()">→</button></footer></section>
 <section class="card space-y-4"><h2 class="text-xl font-semibold">{{label('events')}}</h2><p class="text-sm text-gray-500">{{label('eventHint')}}</p><div class="flex flex-wrap gap-4"><button v-for="event in events" :key="event.id" class="rounded-lg border p-3 text-left dark:border-dark-700" @click="inspectEvent(event.id)">#{{event.id}} · {{time(event.reset_at)}} · {{label(event.status==='observed'?'observed_status':event.status)}}</button></div><div class="flex justify-end gap-3"><span>{{eventTotal}} · {{eventPage}}</span><button class="btn btn-secondary" :disabled="eventPage<=1" @click="eventTurn(-1)">←</button><button class="btn btn-secondary" :disabled="eventPage*20>=eventTotal" @click="eventTurn(1)">→</button></div></section>
 <section class="card space-y-4"><h2 class="text-xl font-semibold">{{label('accountStates')}}</h2><div class="overflow-auto"><table class="table"><thead><tr><th>{{label('account')}}</th><th>{{label('utilization')}}</th><th>{{label('nextReset')}}</th><th>{{label('candidate')}}</th><th>{{label('observed')}}</th><th>{{label('error')}}</th></tr></thead><tbody><tr v-for="state in runtime?.account_states||[]" :key="state.account.id"><td>{{state.account.name}} #{{state.account.id}}</td><td>{{state.utilization??'—'}}% <span v-if="state.suspected_drop" class="text-amber-600">{{label('suspected')}}</span></td><td>{{time(state.next_reset_at)}}</td><td>{{time(state.candidate_reset_at)}}</td><td>{{time(state.observed_at)}}</td><td>{{state.error}}</td></tr></tbody></table></div></section>
 <BaseDialog :show="!!selected" :title="label('recordDetail')" @close="selected=null"><template v-if="selected"><p>{{label('source')}}：{{label(selected.record.source)}} · {{label(selected.record.evidence_type)}}</p><p class="mt-2 text-sm">{{label('requestID')}}：{{selected.record.request_id||'—'}}</p><p class="mt-2 text-sm">{{label('detected')}}：{{time(selected.record.detected_at)}}</p><p class="mt-3 text-red-600">{{selected.record.error_message}}</p><div v-if="selected.delivery" class="my-4 space-y-3"><p>{{label(selected.delivery.database_status)}} · {{label(selected.delivery.cache_status)}} · HTTP {{selected.delivery.http_status??'—'}}</p><p class="text-sm text-gray-500">{{label('reconcileHint')}}</p><button class="btn btn-secondary" :disabled="reconciling||['pending','inflight'].includes(selected.delivery.status)" @click="reconcile">{{label('reconcile')}}</button></div><div v-if="selected.carryover" class="my-4"><p>{{label('weekly_carryover')}} · {{label(selected.carryover.status)}} · {{label(selected.carryover.cache_status)}}</p><p class="text-red-600">{{selected.carryover.error_message}}</p></div><div v-if="selected.record.source==='enhance'&&selected.record.status==='succeeded'&&(selected.delivery||selected.carryover)" class="my-4 space-y-2"><p class="text-sm text-gray-500">{{label('repairHint')}}</p><button class="btn btn-secondary" :disabled="reconciling" @click="repairCache">{{label('repairCache')}}</button></div><details open class="mt-4"><summary>{{label('raw')}}</summary><pre class="mt-3 overflow-auto whitespace-pre-wrap break-all text-xs">{{JSON.stringify(selected,null,2)}}</pre></details></template></BaseDialog>
<BaseDialog :show="!!eventDetail" :title="label('events')" @close="eventDetail=null"><pre class="overflow-auto whitespace-pre-wrap break-all text-xs">{{JSON.stringify(eventDetail,null,2)}}</pre></BaseDialog>
</main></template>
